coderefinery/social-coding

guide.md, talk.md
=> Second iteration of lesson redesign

README.md
Based on the poll used for the non-Git workshop on the 18-20 May 2020, designed by Sabry.
Please feel free to modify if the style should not be like this (i.e., block of code).
=> Addition of poll question and answer alternatives

talk.md
was done by Sabry but never merged. PR was closed).
=> add link to fix #38

README.md
=> Add zoom poll questions

README.md
=> Make question plural

README.md, talk.md
- punctuation
- typos
(mostly in the poll options)
- added link to the EU DB directive
=> Small fixes (punctuation etc.)

.gitignore, Makefile, content/conf.py, content/guide.rst, content/index.rst, content/licensing.md, content/quick-reference.rst, content/social_coding.md, content/software_citation.md, make.bat, requirements.txt
content of talk.md moved into sphinx lesson template.
Draft until all keypoints, other boxes etc are filled.
Exercise suggestions as usual very welcome.
Please review and add comments and issues on things that should be updated better :)
=> Sphinxyphying social coding lesson closes #58

.github/workflows/sphinx.yml
- also need to add github token to repo.
=> fix #60 add generation of webpages with sphinx

content/conf.py, content/css/style.css
- copied from documentation lesson
=> use different colors for boxes, not all blue 

content/conf.py, requirements.txt
- Only appears when built on CR Github Pages
- Review: automerge
=> Add CodeRefinery branding

content/social_coding.md
1. Simplify some discussion points to get more info in less time
=> Touch-ups for may workshop

content/social_coding.md
- Review: does this make the text too long?
=> content/social_coding: Some comments on "sharing is scary"

content/licensing.md
- Closes #98, thanks to @bclaremar!
- Review: automerge
=> content/licensing: Fix broken link

content/licensing.md, content/social_coding.md, content/software_citation.md
- No content changes
- Review: automerge
=> Adjust exercise titles and add exercise headings to match best practices

content/index.rst
=> content/index: toctree can be hidden (it is redundant with the table above)

content/licensing.md
- The previous page ended on 4, I guess this should follow from there.
- Or, it could be "1" again.
- Review: confirm the desire
=> content/licensing: Renumber discussion question to 5

content/exercises.md
- So it doesn't appear so empty, since this lesson is discussion-based.
- Review: consider if this is wanted
=> content/exercises: Add the discussions to the exercise list

content/social-coding.md
- Review: read option and confirm.
=> content/social-coding: Q1, add another option from audience suggestion

content/index.rst, content/sharing.md
lesson was before in reproducible research lesson
* moved the md file here 
* added to index
=> add sharing lesson

content/sharing-data.md
The previous PR brought my curiousity here 😅
Note: The ELIXIR-NO links looks dubious, but it was the only one I found linking to a readable text listing the non-sensitive and sensitive data-sharing services. I see now that our websites are not good for users :(
CC @korbinib
=> Fixed NBIS and ELIXIR-NO data sharing links

content/sharing-data.md
Hello Sabry, I'm trying the pull request again - added a repository to the sharing-data.md file
=> Added DMPortal to sharing-data.md

content/software-citation.md
I have been wanting to do this for a long time. This should be short enough to make people curious and it can be skipped if there is no time to discuss this.
=> Adding a box about FAIR4RS
